spring:
  application:
    name: gmdb
  r2dbc:
    pool:
      max-acquire-time: 30000
      max-size: 10
      min-idle: 5
      max-idle-time: 60000
      max-life-time: 180000
    mybatis:
      r2dbc-url: r2dbc:postgresql://meyernas01.local:1970/gmdb
      username: gmdb_app_user
      password: ${GMDB_APP_USER_PASSWORD}
  threads:
    virtual:
      enabled: true

  graphql:
    graphiql:
      enabled: true

r2dbc:
  mybatis:
    configuration:
      jdbc-type-for-null: null
    type-handlers-package: com.yellowmoonsoftware.gmcatalog.gmdb.api.mybatis.typehandlers

logging:
  level:
    com.yellowmoonsoftware.gmcatalog.gmdb.api.mybatis.mappers: debug
    com.yellowmoonsoftware.gmcatalog.gmdb.api.mybatis.typehandlers: info
    org.springframework.graphql: debug
    com.yellowmoonsoftware.graphql.multipart: debug
file-service:
  root: ${FILE_SERVICE_ROOT}