spring:
  application:
    name: gmdb
  r2dbc:
    pool:
      max-acquire-time: 30000
      max-size: 10
      min-idle: 5
      max-idle-time: 60000
      max-life-time: 180000
    mybatis:
      r2dbc-url: ${GMDB_URL}
      username: gmdb_app_user
      password: ${GMDB_APP_USER_PASSWORD}
  threads:
    virtual:
      enabled: true

  graphql:
    graphiql:
      enabled: true

r2dbc:
  mybatis:
    configuration:
      jdbc-type-for-null: null

file-service:
  root: ${FILE_SERVICE_ROOT}
